image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
  - port: 9000-9999
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false

tasks:
  - init: ./mvnw install -DskipTests=false
  - command: mysql -e "show databases;"
  - command: python3 -m http.server 8080
  - command: gp preview $(gp url 8080)/workspace/rquarkusweb/src/main/resources/META-INF/resources/index.html